on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
      latest:
        type: boolean
        default: ${{ github.ref == 'refs/heads/main' }}
      build_dep:
        type: string
        default: ""
      runs-on:
        type: string
        default: ubuntu-latest
      runs-on-amd64:
        type: string
        default: ubuntu-latest
      runs-on-arm64:
        type: string
        default: ubuntu-latest-arm
      force-arm-build:
        type: boolean
        default: false
      arch:
        type: string
        default: '["amd64", "arm64"]'
jobs:
  source:
    runs-on: ubuntu-latest
    outputs:
      pkg: ${{ steps.tag.outputs.pkg }}
      version: ${{ steps.tag.outputs.version }}
      skip_build: ${{ steps.tag.outputs.skip_build }}
      skip_release: ${{ steps.tag.outputs.skip_release }}
    steps:
      - uses: actions/checkout@v4
      - name: resolve container digest
        run: |
          if [ ! -e .container ]; then
            image="ghcr.io/gardenlinux/repo-debian-snapshot"
            podman pull "$image"
            digest="$(podman image inspect --format '{{ .Digest }}' "$image")"
            echo "$image@$digest" > .container
          fi
      - name: set release version suffix
        if: inputs.release
        run: |
          echo 'version_suffix=gl0' >> prepare_source
      - name: commit
        if: inputs.release
        run: |
          git checkout --detach HEAD
          git add .
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -m "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: build source pkg
        run: |
          dir="$(mktemp -d)"
          git clone --depth=1 https://github.com/gardenlinux/package-build "$dir/package-build"
          "$dir/package-build/build" --source-only .
      - uses: actions/upload-artifact@v4
        with:
          name: source
          include-hidden-files: true
          path: |
            .
            !.git
      - id: tag
        name: check version
        run: |
          ls -lah .build
          pkg="$(awk -F ': ' '$1 == "Source" { print $2 }' < .build/*.dsc)"
          version="$(awk -F ': ' '$1 == "Version" { print $2 }' < .build/*.dsc | tr '~' '+')"
          version="${version#*:}"
          echo "pkg=$pkg" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          if [[ "$version" != *"+dev" ]]; then
            git fetch --tags
            if git rev-list "$version" > /dev/null 2>&1; then
              echo "$version already exists"
              echo skip_build=true >> "$GITHUB_OUTPUT"
              echo skip_release=true >> "$GITHUB_OUTPUT"
            else
              git tag "$version"
              git push origin "$version"
            fi
          else
            echo skip_release=true >> "$GITHUB_OUTPUT"
          fi
  binary:
    runs-on: ${{ matrix.arch == 'amd64' && inputs.runs-on-amd64 || matrix.arch == 'arm64' && inputs.runs-on-arm64 || inputs.run-on }}
    needs: source
    if: ${{ ! needs.source.outputs.skip_build }}
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJSON(inputs.arch) }}
    steps:
      - if: matrix.arch == 'amd64'
        run: |
          sudo rm -rf /{usr/{local/{lib/{android,heroku},.ghcup,share/{dotnet,powershell,miniconda,swift}},share/{dotnet,miniconda,swift}},opt/{hostedtoolcache,microsoft},imagegeneration}
          sudo docker system prune -a -f
      - if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends podman uidmap slirp4netns gh
      - uses: actions/download-artifact@v4
        with:
          name: source
      - name: fetch build dependencies
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir build_dep
          while read repo tag; do
            if [ -n "$repo" ] && [ -n "$tag" ]; then
              gh release download --dir build_dep --repo "$repo" "$tag"
            fi
          done <<< "$(cat << 'EOF'
          ${{ inputs.build_dep }}
          EOF
          )"
      - name: build binary pkg
        run: |
          dir="$(mktemp -d)"
          git clone --depth=1 https://github.com/gardenlinux/package-build "$dir/package-build"
          arch="${{ matrix.arch }}"
          build=binary
          if [ "$arch" = arm64 ] && [ '${{ inputs.force-arm-build }}' != true ]; then
            build=any
          fi
          "$dir/package-build/build" --binary-only --arch "$arch" --build "$build" .
      - uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.arch }}
          include-hidden-files: true
          path: .build
  release:
    runs-on: ubuntu-latest
    needs: [source, binary]
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJSON(inputs.arch) }}
    if: ${{ ! needs.source.outputs.skip_release }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binary-${{ matrix.arch }}
          path: .build
      - name: publish release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -lah .build
          pkg="${{ needs.source.outputs.pkg }}"
          version="${{ needs.source.outputs.version }}"
          tar -C .build -cv . | xz | split --bytes=1G --suffix-length=4 --numeric-suffix - build.tar.xz.
          gh release create "$version" --latest=${{ inputs.latest }} --verify-tag --title "${pkg}_${version}" --notes "created by GitHub actions run [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" build.tar.xz.*
